# Generated by Django 3.0.2 on 2020-03-22 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('sitioweb', models.URLField()),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
            ],
            options={
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=40)),
                ('departamento', models.CharField(max_length=60)),
                ('ciudad', models.CharField(max_length=90)),
            ],
            options={
                'verbose_name_plural': 'Origenes',
                'ordering': ['pais'],
            },
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estilo', models.CharField(max_length=50)),
                ('sabor', models.CharField(max_length=50)),
                ('aroma', models.CharField(max_length=50)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('portada', models.ImageField(upload_to='portadas')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.Marca')),
            ],
            options={
                'verbose_name_plural': 'Variedades',
                'ordering': ['estilo'],
            },
        ),
        migrations.AddField(
            model_name='marca',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.Origen'),
        ),
    ]
